SSPROD-10240-M replace ".." concatenation with table.concat
draios/oss-falco pull request #21
Opened 2021-12-17 18:06 UTC by VadimZy

**Which issue(s) this PR fixes**:
OOM error when parsing big Falco tuner files

Fixes #

**Special notes for your reviewer**:
The original code formating was not perfect - a mix of 2,3,4 indentations

Please use ignore whitespace when reviewing.

**Does this PR introduce a user-facing change?**:
"NONE" 

```release-note

```

2021-12-20 17:52 UTC, mstemm requested changes

2021-12-20 17:52 UTC, mstemm commented on userspace/engine/lua/rule_loader.lua
> +            icond[#icond + 1] = fields[k] .. " " .. comps[k] .. " " .. istr
This one probably isn't as important, as it's just 3 big blocks of text per exception fields + values, but you might want to table concat here too.

2021-12-20 17:52 UTC, mstemm commented on userspace/engine/lua/rule_loader.lua
> +    local ret = table.concat(icond)
I didn't double-check, but does concatenating directly with no spaces give you a meaningful condition snippet?

2022-01-02 22:02 UTC, VadimZy commented on userspace/engine/lua/rule_loader.lua
> +            icond[#icond + 1] = fields[k] .. " " .. comps[k] .. " " .. istr
I thought about it but then we will create a temp table for each iteration and we might have the same mem consumption. To clean up, we probably should take this piece in a separate func. In our tests, this was a problem anyway.

2022-01-02 22:03 UTC, VadimZy commented on userspace/engine/lua/rule_loader.lua
> +    local ret = table.concat(icond)
Yes, the rules (exceptions) were correct.

2022-01-02 22:07 UTC, VadimZy commented on userspace/engine/lua/rule_loader.lua
> +                        istr = istr .. ", "
It was not a problem when I run tests, probably cuz `local istr = ""` local gets collected on each iteration

2022-01-02 22:12 UTC, VadimZy commented
@mstemm @ivanlysiuk-sysdig closing this due to base divergence; new opened 
https://github.com/draios/oss-falco/pull/22

2022-01-02 22:12 UTC, closed without merging